### ISSUE TITLE
Papirus wont work on new Raspberry Pi Zero W

### ISSUE THREAD

**Issue by extremepilot** [PiSupply/PaPiRus#115]
I recently purchased the new wireless Raspberry Pi Zero and tried to use my Papirus screen with it, but it will not work and I get one of a number of errors, images attached. I have confirmed the display works on the regular Pi Zero and the Pi 3-B.

![image1](https://cloud.githubusercontent.com/assets/28110229/25494927/57e8ce8e-2b49-11e7-9502-5a45c4f7cbd7.PNG)
![img_6752](https://cloud.githubusercontent.com/assets/28110229/25494928/57ef3c74-2b49-11e7-96b7-547e4b95d98b.PNG)

**Comment by shawaj** [comment]
Are you using Raspbian?

Have you tried with a fresh image and got it fully updated first?

Thanks

**Comment by extremepilot** [comment]
Yeah, I have updated everything multiple times. I have also tried both Raspbian and Raspbian lite.

**Comment by shawaj** [comment]
@francesco-vannini any ideas here? I've not seen any issues with the Raspberry Pi Zero Wireless have you?

@extremepilot what header have you soldered to the Pi?

**Comment by francesco-vannini** [comment]
There are no known problems with any of the Raspberry Pis. Have tested for the last PR with a Zero W too. If you have correctly enabled SPI and I2C (which are now enabled by default from our script anyway) I suspect something dodgy is happening with your Zero @extremepilot . I'll keep this open for a while so that you can get back to us on how this goes.

**Comment by extremepilot** [comment]
Issue seems to be resolved on Raspbian, will confirm for Raspbian lite soon.

**Comment by shawaj** [comment]
@extremepilot perfect thanks

**Comment by extremepilot** [comment]
Still having issues with Raspbian lite, with regular Raspbian the issue seemed to exist with NOOBS 2.3 and was resolved with NOOBS 2.4.

**Comment by francesco-vannini** [comment]
For Raspbian lite I have used the April release and all is ok. What error do you get now? Are you using the April release and flash directly on SD?

**Comment by extremepilot** [comment]
I am using the most up to date version of NOOBS (2.4, 4/10) to install Raspbian lite onto the microSD card.
![fullsizerender](https://cloud.githubusercontent.com/assets/28110229/25545069/3d54b294-2c2b-11e7-919d-1a3716cd6516.jpg)

**Comment by shawaj** [comment]
Looks like smbus hasn't installed properly? 

Thought we added this to the install script @francesco-vannini ?

**Comment by extremepilot** [comment]
The issue seems to be solved on both instances of Raspbian. Sorry for the confusion, there are a lot of steps to setup PaPiRus that one can get lost in. The final issue for me seemed to be enabling i2c and SPI.

**Comment by francesco-vannini** [comment]
I am glad it all works now but I fail to see the many steps involved in setting up the PaPiRus as all is done now via the one liner at the top of the README file.
Running
curl -sSL https://pisupp.ly/papiruscode | sudo bash
should do everything you need.
Did you by any chance follow the manual setup instead for some reason? Because that wasn't clear to me.
Anyways all good in the end, I'll go ahead and close the issue.
