### ISSUE TITLE
Any guide for production use?

### ISSUE THREAD

**Issue by CraigglesO** [PiSupply/PaPiRus#139]
I was hoping on making a device (for fun) using only the screen. Is there any resources you could provide for this?

**Comment by shawaj** [comment]
You can't use only the screen, you would need some kind of microcontroller
to update what's on it.

What's the use case you had in mind?

On 21 Jul 2017 4:51 am, "CraigglesO" <notifications@github.com> wrote:

I was hoping on making a device (for fun) using only the screen. Is there
any resources you could provide for this?

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/PiSupply/PaPiRus/issues/139>, or mute the thread

**Comment by CraigglesO** [comment]
Ah, ok. I see. I was hoping to keep the device as slim as possible. have the screen practically flush with the raspberry pi zero. It's seriously the perfect size, and I just find the e-paper so beautiful. But, with the headers and all, the thickness is a little too much for my taste.

If there was a design that had the pins to connect directly from the back side, that would be enough of a low profile I think. I just don't have enough knowledge of the project.

**Comment by shawaj** [comment]
Have you tried the Pi Zero one? Or perhaps the HAT version with our
official case for it?

**Comment by CraigglesO** [comment]
![alt-1](https://cdn-shop.adafruit.com/1200x900/3335-01.jpg)

This is my setup.

I'm being too picky. This is great. I just got a 3d printer, and I'll make a case with this setup :)

**Comment by shawaj** [comment]
You could try removing the plastic from the header and cutting the pins
shorter?

**Comment by CraigglesO** [comment]
Huh, yeah. I should try that! Honestly, that should work fine! I'll close this as it is solved.
