### ISSUE TITLE
papirus-system and other examples

### ISSUE THREAD

**Issue by cmseal** [PiSupply/PaPiRus#66]
This is mentioned in the readme, but not in the bin folder. 

Likewise, any other examples from yourself or others would be really helpful, as I'm still learning python! :)

**Comment by shawaj** [comment]
We will be adding more samples in the coming months to build the PaPiRus
platform :-)

**Comment by cmseal** [comment]
Great, thanks for the quick response! Seemed like a cool piece of kit to play with, along with the servos and cameras I'm playing with using six Pi zeros! :)

Look forward to seeing some of the cool things that can be done with PaPiRus!

**Comment by shawaj** [comment]
Thanks.

We should have a software developer on our team full time soon so our
output on that side will be hugely amplified :-)

On 14 Dec 2016 11:20 pm, "Chris Seal" <notifications@github.com> wrote:

Great, thanks for the quick response! Seemed like a cool piece of kit to
play with, along with the servos and cameras I'm playing with using six Pi
zeros! :)

Look forward to seeing some of the cool things that can be done with
PaPiRus!

—
You are receiving this because you commented.

Reply to this email directly, view it on GitHub
<https://github.com/PiSupply/PaPiRus/issues/66#issuecomment-267188158>, or mute
the thread
