### ISSUE TITLE
Invert display so the Pi can have any orientation

### ISSUE THREAD

**Issue by mashedkeyboard** [PiSupply/PaPiRus#90]
I'd love to be able to use PaPiRus with my Pi Zero "upside down" as considered by the PaPiRus HAT - with the text being displayed the right way up.

Could we have a "setOrientation()" in a future build?

**Comment by shawaj** [comment]
Related to #84

**Comment by shawaj** [comment]
In framebuffer / fbtft this can be done by specifying clockwise rotations from standard - 90, 180, 270 - think this would be our best bet

**Comment by Dom1n1c** [comment]
i would like to have an option which allows me to rotate the screen by 180° 
(to attach the RPi Zero W to the Wall and to have the cable running underneath)

**Comment by shawaj** [comment]
Yes this is a very good idea for sure. We will definitely look into it.

**Comment by Dom1n1c** [comment]
Hey @shawaj 
Now, since the PaPiRus is working with the latest kernel on my Pi Zero W, I would like to have the correct orientation on my ePaper. 
Is there any way to do this before: image.write? 
I only display Text right now, so inverting the font would be to complicated. 
Instead: Displaying an image could easily be manipulated.

**Comment by shawaj** [comment]
Do you need to write text on the fly?

Otherwise​ you could generate images, save then upside down, and send to
screen?

On 24 Mar 2017 8:15 am, "Dominic Spatz" <notifications@github.com> wrote:

Hey @shawaj <https://github.com/shawaj>
Now, since the PaPiRus is working with the latest kernel on my Pi Zero W, I
would like to have the correct orientation on my ePaper.
Is there any way to do this before: image.write?
I only display Text right now, so inverting the font would be to
complicated.
Instead: Displaying an image could easily be manipulated.

—
You are receiving this because you were mentioned.

Reply to this email directly, view it on GitHub
<https://github.com/PiSupply/PaPiRus/issues/90#issuecomment-288959463>, or mute
the thread

**Comment by Dom1n1c** [comment]
Thats my code:
https://github.com/Dom1n1c/PaPiRus-MQTT/

**Comment by shawaj** [comment]
What does the code do? If you want it included in the PaPiRus repository
can you submit a PR

Thanks

**Comment by Dom1n1c** [comment]
it listens for mqtt topics and then it'll print them to the display 😄 
Here you can find a picture of the PaPiRus Zero running this script
https://community.openhab.org/t/using-an-epaper-eink-display-as-energy-temperature-monitor-mqtt/16954/2

**Comment by Dom1n1c** [comment]
Any news on rotating the screen (changing the orientatiion)?

Thanks :)

**Comment by francesco-vannini** [comment]
Hi @Dom1n1c, I believe that would in fact require some work on the EPD driver what do you think @tvoverbeek ?

**Comment by tvoverbeek** [comment]
@Dom1n1c @francesco-vannini  No need to modify the repaper/gratis driver.
Should be possible to handle this on the python side using the PIL library.
But requires careful splitting of physical screen coordinates  and size (post rotation) and virtual screen coordinates and size (pre rotation).
180 deg should be easier (no change in screen height and width), 90 and 270 requires more work

**Comment by quavoce** [comment]
I too would really like this feature please. 
My use case would be to have dynamically updating text aligned next to the buttons on a PiZero, in portrait mode with the 2″ diagonal (200 x 96 resolution) display. 
If I could write text in portrait mode (90 degrees), I would position the text using x/y values.
I do realise I could use multiple images for each button status, but having dynamic text would be easier.
Thanks!

**Comment by tvoverbeek** [comment]
See my PR #119 Hopefully will get merged soon. Otherwise clone my repository

**Comment by quavoce** [comment]
Brilliant! Can't wait to try this out, thank you!

**Comment by shawaj** [comment]
Think @francesco-vannini was playing with this but got distracted with some other stuff at tail end of last week. Will get it merged this coming week :-)

**Comment by francesco-vannini** [comment]
We are reviewing a PR for this and we are aiming to merge next week.

**Comment by francesco-vannini** [comment]
Sorted in #119
